name: Trigger AWS CodePipeline
description: A GitHub Action to trigger an AWS CodePipeline execution.

inputs:
  pipeline_name:
    description: The name of the AWS CodePipeline to trigger.
    required: true
  branch_or_tag:
    description: The branch or tag to use for the pipeline source.
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.pipeline_name }}
    - ${{ inputs.branch_or_tag }}

