name: 'Trigger AWS CodePipeline'
description: 'A GitHub Action to trigger an AWS CodePipeline execution with a specific branch or tag.'
author: 'vo minh luan'
inputs:
  pipeline_name:
    description: 'The name of the AWS CodePipeline to trigger'
    required: true
  branch_or_tag:
    description: 'The branch or tag to use for the pipeline source'
    required: true
outputs:
  execution_id:
    description: 'The execution ID of the triggered pipeline'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: 'blue'
  icon: 'server'
